pagination:
  transaction_limit: 64
  finance_detailing_limit: 32

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    default:
      format: "%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d | %(message)s"

  handlers:
    console:
      level: DEBUG
      class: logging.StreamHandler
      formatter: default
      stream: ext://sys.stdout

    app_file:
      level: INFO
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: "logs/app.log"
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf8

    services_file:
      level: DEBUG
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: "logs/services.log"
      maxBytes: 10485760
      backupCount: 5
      encoding: utf8

    repositories_file:
      level: DEBUG
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: "logs/repositories.log"
      maxBytes: 10485760
      backupCount: 5
      encoding: utf8

    routers_file:
      level: DEBUG
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: "logs/routers.log"
      maxBytes: 10485760
      backupCount: 5
      encoding: utf8

  loggers:
    src.services:
      level: DEBUG
      handlers: [services_file, console]
      propagate: false

    src.repositories:
      level: DEBUG
      handlers: [repositories_file, console]
      propagate: false

    src.api.routers:
      level: DEBUG
      handlers: [routers_file, console]
      propagate: false

  root:
    level: INFO
    handlers: [app_file, console]
