"""create_initial_tables

Revision ID: 5c6caffc3ae5
Revises:
Create Date: 2025-08-29 17:15:26.568022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c6caffc3ae5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "finance_detailing",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("initial_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "total_income",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "total_expense",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "profit_estimated",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "profit_real",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "after_amount_net",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "after_amount_gross",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finance_detailing_id"), "finance_detailing", ["id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("note", sa.String(255), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "made_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_finance_detailing_id"), table_name="finance_detailing")
    op.drop_table("finance_detailing")
    # ### end Alembic commands ###
